CREATE TABLE EMPLOYEE(
EMPLOYEE_ID INTEGER NOT NULL AUTO_INCREMENT,
AGE INTEGER,
DESCRIPTION VARCHAR(255),
EMAIL VARCHAR(255),
FIRSTNAME VARCHAR(255),
LASTNAME VARCHAR(255),
SEX VARCHAR(255),
FULLNAME VARCHAR(255),
POSITION_ID INTEGER,
HOTEL_ID INTEGER,
PRIMARY_KEY(EMPLOYEE_ID));
