INSERT INTO "PUBLIC"."POSITIONS"( "POSITION_ID", "DESCRIPTION" ) VALUES (0 , 'Pokojowa');
INSERT INTO "PUBLIC"."POSITIONS"( "POSITION_ID", "DESCRIPTION" ) VALUES (1 , 'Lobby');
INSERT INTO "PUBLIC"."POSITIONS"( "POSITION_ID", "DESCRIPTION" ) VALUES (2 , 'Spa');