package com.planner.enums;

public enum Hours {
	ONE_AM,TWO_AM,THREE_AM,FOUR_AM,FIVE_AM,SIX_AM,SEVEN_AM,EIGHT_AM,NINE_AM,TEN_AM,ELEVEN_AM,TWELVE_AM,
	ONE_PM,TWO_PM,THREE_PM,FOUR_PM,FIVE_PM,SIX_PM,SEVEN_PM,EIGHT_PM,NINE_PM,TEN_PM,ELEVEN_PM,TWELVE_PM
}
